List<String> countyDrop = [
  'Select One',
  'Aberdeenshire',
  'Angus',
  'Antrim',
  'Argyll & Bute',
  'Armagh',
  'Ayrshire',
  'Banffshire',
  'Bath and North East Somerset',
  'Bedfordshire',
  'Berkshire',
  'Berwickshire',
  'Blaenau Gwent',
  'Borders',
  'Bridgend',
  'Bristol',
  'Buckinghamshire',
  'Caerphilly',
  'Caithness',
  'Cambridgeshire',
  'Cardiff',
  'Carmarthenshire',
  'Ceredigion',
  'Cheshire',
  'Clackmannanshire',
  'Conwy',
  'Cornwall',
  'County Durham',
  'Cumbria',
  'Denbighshire',
  'Derbyshire',
  'Devon',
  'Down',
  'Dumfries & Galloway',
  'Dunbartonshire',
  'East Ayrshire',
  'East Dunbartonshire',
  'East Lothian',
  'East Renfrewshire',
  'East Riding of Yorkshire',
  'East Sussex',
  'Essex',
  'Fermanagh',
  'Fife',
  'Flintshire',
  'Gloucestershire',
  'Greater London',
  'Greater Manchester',
  'Gwynedd',
  'Hampshire',
  'Herefordshire',
  'Hertfordshire',
  'Highland',
  'Inverclyde',
  'Isle of Anglesey',
  'Isle of Wight',
  'Isles of Scilly',
  'Kent',
  'Kincardineshire',
  'Lancashire',
  'Leicestershire',
  'Lincolnshire',
  'Londonderry',
  'Merseyside',
  'Merthyr Tydfil',
  'Midlothian',
  'Monmouthshire',
  'Moray',
  'Neath Port Talbot',
  'Newport',
  'Norfolk',
  'North Ayrshire',
  'North Lanarkshire',
  'North Somerset',
  'North Yorkshire',
  'Northamptonshire',
  'Northumberland',
  'Nottinghamshire',
  'Orkney',
  'Oxfordshire',
  'Pembrokeshire',
  'Perth & KInross',
  'Powy',
  'Renfrewshire',
  'Rhondda Cynon Taff',
  'Rutland',
  'Shetland',
  'Shropshire',
  'Somerset',
  'South Ayrshire',
  'South Gloucestershire',
  'South Lanarkshire',
  'South Yorkshire',
  'Staffordshire',
  'Stirlingshire',
  'Suffolk',
  'Surrey',
  'Swansea',
  'Torfaen',
  'Tyne & Wear',
  'Tyrone',
  'Vale of Glamorgan',
  'WIltshire',
  'Warwickshire',
  'West Dunbartonshire',
  'West Lothian',
  'West Midlands',
  'West Sussex',
  'West Yorkshire',
  'Western Isles',
  'Worcestershire',
  'Wrexham'
];
